name: CI Phase

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_and_test:
    name: Build the java app
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'corretto'
        
      - name: Build source code with Maven
        run: mvn install 

      - name: check artifacts
        run: |
          ls -al target

      - name: Version artifacts
        run: |
          mv target/*.war target/vprofile-v2-${{ github.run_number }}.war

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: vprofile-v2-${{ github.run_number }}.war
          path: target/*.war

     
      

    
    
    
      

  
  
  

