name: CI Phase

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Artifacts_Build_and_test:
    name: Build the java app
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'corretto'
        
      - name: Build source code with Maven
        run: mvn install 

      - name: check artifacts
        run: |
          ls -al target

      - name: Version artifacts
        run: |
          mv target/*.war target/vprofile-v2-${{ github.run_number }}.war

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: vprofile-v2-${{ github.run_number }}.war
          path: target/*.war

  Image_Build:
    name: Build app image
    runs-on: ubuntu-22.04
    needs: [ Artifacts_Build_and_test ]
    env: 
      repository_name: vprofile-app
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository_name }}:${{ github.run_number }}

      - name: Check app image
        run: |
          docker images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository_name }}:${{ github.run_number }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

    
    
    
      

  
  
  

