name: first action

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: Prebuild
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: cat file.txt
        run: cat file.txt
  second_job:
    name: Install dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt install
          sudo apt upgrade -y
          sudo apt install wget
          sudo apt install apache2
